import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import { drizzle } from "drizzle-orm/postgres-js";

/**
 * Standalone migration runner: `pnpm --filter @ratify/db run migrate`.
 * Applies all SQL files generated by drizzle-kit under ./drizzle.
 */
async function main() {
  const connectionString = process.env.DATABASE_URL ?? "postgres://ratify:ratify@localhost:5432/ratify";
  const sql = postgres(connectionString, { max: 1 });
  const db = drizzle(sql);

  console.log(`Applying migrations from ./drizzle against ${connectionString.replace(/:[^:]*@/, ":****@")}`);
  await migrate(db, { migrationsFolder: "./drizzle" });
  console.log("Migrations applied successfully.");

  await sql.end();
}

main().catch((err) => {
  console.error("Migration failed:", err);
  process.exit(1);
});
