import { sql } from "drizzle-orm";
import { timestamp, uuid } from "drizzle-orm/pg-core";

/** Standard primary key column: UUID, generated by Postgres. */
export const idColumn = () => uuid("id").primaryKey().default(sql`gen_random_uuid()`);

/** Standard created/updated timestamp pair used on every table. */
export const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
};
