import { readFileSync, existsSync } from "node:fs";
import path from "node:path";

interface EvalRow {
  pr: { owner: string; repo: string; number: number; expected: string };
  title: string | null;
  filesFetched: number;
  policyFindings: number;
  policyFindingKeys: string[];
  llmFindings: number | null;
  llmSummary: string | null;
  llmError: string | null;
  policyMs: number;
  llmMs: number | null;
  totalMs: number;
}

interface EvalReport {
  generatedAt: string;
  totalPrs: number;
  totalPolicyFindings: number;
  totalLlmFindings: number;
  avgPolicyMs: number;
  avgLlmMs: number | null;
  ruleFireFrequency: Record<string, number>;
  rows: EvalRow[];
}

function loadReport(): EvalReport | null {
  const p = path.join(process.cwd(), "public", "eval-results.json");
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, "utf-8")) as EvalReport;
  } catch {
    return null;
  }
}

export default function BenchmarksContent() {
  const report = loadReport();

  return (
    <div className="mx-auto max-w-[1000px] px-8 fade-up">
      <h1 className="text-4xl sm:text-5xl tracking-tight mb-6 font-bold" style={{ fontFamily: "var(--font-heading)" }}>
        Benchmarks
      </h1>
      <p className="text-lg text-secondary leading-relaxed max-w-2xl mb-4">
        Every number on this page is generated by an eval harness that runs Ratify&apos;s real
        pipeline against real merged pull requests from public repositories. No marketing
        estimates, no hand-picked wins &mdash; if you don&apos;t trust it, the source is at{" "}
        <a href="https://github.com/taxcollector23/ratify/blob/main/eval/run-eval.ts" className="text-primary hover:text-primary-hover">
          eval/run-eval.ts
        </a>{" "}
        and the PR set is at{" "}
        <a href="https://github.com/taxcollector23/ratify/blob/main/eval/pr-set.json" className="text-primary hover:text-primary-hover">
          eval/pr-set.json
        </a>
        .
      </p>
      <p className="text-sm text-muted max-w-2xl mb-16">
        This is a v0 eval set (~14 PRs across major open-source projects). Precision/recall
        against human ground-truth requires labeling and is intentionally not shown until it
        can be reported honestly. What&apos;s shown below is what the pipeline actually did.
      </p>

      {report ? <ReportView report={report} /> : <p className="text-danger">No eval results found. Run <code>npx tsx eval/run-eval.ts</code> and redeploy.</p>}
    </div>
  );
}

function ReportView({ report }: { report: EvalReport }) {
  const ok = report.rows.filter((r) => r.filesFetched > 0);
  const fetchFailures = report.rows.length - ok.length;
  const generated = new Date(report.generatedAt);

  return (
    <>
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 mb-16 pb-12 border-b border-border">
        <Stat label="PRs evaluated" value={String(ok.length)} sub={fetchFailures > 0 ? `${fetchFailures} fetch failure${fetchFailures === 1 ? "" : "s"} skipped` : undefined} />
        <Stat label="Policy findings" value={String(report.totalPolicyFindings)} sub={`across ${countPrsWithFindings(ok, "policy")} PR${countPrsWithFindings(ok, "policy") === 1 ? "" : "s"}`} />
        <Stat label="LLM findings" value={String(report.totalLlmFindings)} sub={`across ${countPrsWithFindings(ok, "llm")} PR${countPrsWithFindings(ok, "llm") === 1 ? "" : "s"}`} />
        <Stat label="Avg policy latency" value={`${report.avgPolicyMs}ms`} sub={report.avgLlmMs !== null ? `LLM: ${report.avgLlmMs}ms` : undefined} />
      </div>

      <h2 className="text-2xl font-semibold text-foreground mb-2">Deterministic rule fire frequency</h2>
      <p className="text-sm text-secondary mb-6 max-w-2xl">
        Which deterministic policy rules fired against the eval set, and how often. Rules that
        never fire against this set aren&apos;t noisy &mdash; they&apos;re calibrated for real
        issues that the eval set doesn&apos;t contain.
      </p>
      <div className="rounded-xl border border-border overflow-x-auto mb-16">
        <div className="min-w-[420px]">
          <div className="grid grid-cols-[1fr_120px] gap-4 px-5 py-3 text-xs font-semibold text-muted uppercase tracking-wider bg-surface">
            <span>Rule key</span>
            <span>Fired</span>
          </div>
          {Object.keys(report.ruleFireFrequency).length === 0 ? (
            <div className="px-5 py-4 text-sm text-muted">No deterministic rule fired against this eval set.</div>
          ) : (
            Object.entries(report.ruleFireFrequency)
              .sort(([, a], [, b]) => b - a)
              .map(([rule, n]) => (
                <div key={rule} className="grid grid-cols-[1fr_120px] gap-4 px-5 py-4 border-t border-border items-center">
                  <code className="text-sm text-foreground">{rule}</code>
                  <span className="text-sm text-secondary tabular-nums">{n}</span>
                </div>
              ))
          )}
        </div>
      </div>

      <h2 className="text-2xl font-semibold text-foreground mb-2">Per-PR results</h2>
      <p className="text-sm text-secondary mb-6 max-w-2xl">
        The full evaluated set. Each row is a real merged pull request from a public repo,
        fetched via GitHub&apos;s public API, evaluated with Ratify&apos;s deterministic
        policy engine and then (if the row&apos;s LLM column shows a number) the LLM
        reasoning step.
      </p>
      <div className="rounded-xl border border-border overflow-x-auto mb-16">
        <div className="min-w-[720px]">
          <div className="grid grid-cols-[1fr_80px_70px_70px_100px] gap-4 px-5 py-3 text-xs font-semibold text-muted uppercase tracking-wider bg-surface">
            <span>Pull request</span>
            <span>Files</span>
            <span>Policy</span>
            <span>LLM</span>
            <span>Latency</span>
          </div>
          {report.rows.map((row) => (
            <div
              key={`${row.pr.owner}/${row.pr.repo}#${row.pr.number}`}
              className="grid grid-cols-[1fr_80px_70px_70px_100px] gap-4 px-5 py-4 border-t border-border items-start"
            >
              <div className="min-w-0">
                <a
                  href={`https://github.com/${row.pr.owner}/${row.pr.repo}/pull/${row.pr.number}`}
                  target="_blank" rel="noopener noreferrer"
                  className="text-sm font-medium text-foreground hover:text-primary"
                >
                  {row.pr.owner}/{row.pr.repo}#{row.pr.number}
                </a>
                <div className="text-xs text-secondary mt-0.5 truncate">
                  {row.title ?? <span className="text-danger">fetch failed</span>}
                </div>
              </div>
              <span className="text-sm text-foreground tabular-nums">{row.filesFetched || "—"}</span>
              <span className="text-sm tabular-nums">
                {row.filesFetched === 0 ? <span className="text-muted">—</span> : row.policyFindings > 0 ? <span className="text-warning font-medium">{row.policyFindings}</span> : <span className="text-secondary">0</span>}
              </span>
              <span className="text-sm tabular-nums">
                {row.llmFindings === null ? <span className="text-muted">—</span> : row.llmFindings > 0 ? <span className="text-warning font-medium">{row.llmFindings}</span> : <span className="text-secondary">0</span>}
              </span>
              <span className="text-xs text-muted tabular-nums">
                {row.filesFetched === 0 ? "—" : row.llmMs !== null ? `${(row.llmMs / 1000).toFixed(1)}s` : `${row.policyMs}ms`}
              </span>
            </div>
          ))}
        </div>
      </div>

      <p className="text-xs text-muted mb-2">
        Generated {generated.toUTCString()}. To re-generate, run{" "}
        <code className="text-xs bg-surface border border-border rounded px-1.5 py-0.5">npx tsx eval/run-eval.ts</code>{" "}
        and commit the resulting <code>public/eval-results.json</code>.
      </p>
    </>
  );
}

function Stat({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div>
      <div className="text-3xl sm:text-4xl font-semibold text-foreground mb-1 tabular-nums">{value}</div>
      <div className="text-sm text-secondary">{label}</div>
      {sub && <div className="text-xs text-muted mt-0.5">{sub}</div>}
    </div>
  );
}

function countPrsWithFindings(rows: EvalRow[], kind: "policy" | "llm"): number {
  return rows.filter((r) => (kind === "policy" ? r.policyFindings : r.llmFindings ?? 0) > 0).length;
}
